# Generated by Django 3.1.4 on 2020-12-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201231_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
