# Generated by Django 3.1.4 on 2021-01-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_letter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectTest',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
